// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkiCE1haAXTOWkiKRKj_1evwHKz0r_GFI',
    appId: '1:717147220033:web:9d68e8232a631c5a7ffec0',
    messagingSenderId: '717147220033',
    projectId: 'track-inventory-app',
    authDomain: 'track-inventory-app.firebaseapp.com',
    databaseURL: 'https://track-inventory-app-default-rtdb.firebaseio.com',
    storageBucket: 'track-inventory-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIm53eRGZifTFRqK3BD8CLd2px9tW7OVA',
    appId: '1:717147220033:android:f9d96f5544f779e77ffec0',
    messagingSenderId: '717147220033',
    projectId: 'track-inventory-app',
    databaseURL: 'https://track-inventory-app-default-rtdb.firebaseio.com',
    storageBucket: 'track-inventory-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFl-gEM8_eyVeWHj9mMfcPcKepfT7qgdY',
    appId: '1:717147220033:ios:9b2d43c5a99f211b7ffec0',
    messagingSenderId: '717147220033',
    projectId: 'track-inventory-app',
    databaseURL: 'https://track-inventory-app-default-rtdb.firebaseio.com',
    storageBucket: 'track-inventory-app.firebasestorage.app',
    iosBundleId: 'com.example.trackInvFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFl-gEM8_eyVeWHj9mMfcPcKepfT7qgdY',
    appId: '1:717147220033:ios:9b2d43c5a99f211b7ffec0',
    messagingSenderId: '717147220033',
    projectId: 'track-inventory-app',
    databaseURL: 'https://track-inventory-app-default-rtdb.firebaseio.com',
    storageBucket: 'track-inventory-app.firebasestorage.app',
    iosBundleId: 'com.example.trackInvFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkiCE1haAXTOWkiKRKj_1evwHKz0r_GFI',
    appId: '1:717147220033:web:09372b276f6e94e97ffec0',
    messagingSenderId: '717147220033',
    projectId: 'track-inventory-app',
    authDomain: 'track-inventory-app.firebaseapp.com',
    databaseURL: 'https://track-inventory-app-default-rtdb.firebaseio.com',
    storageBucket: 'track-inventory-app.firebasestorage.app',
  );
}
